/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import admin.data_laporan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.*;
import models.*;

/**
 *
 * @author ASUS
 */
public class Admini extends javax.swing.JFrame {
    private ResultModel user;
    private models.Laporan laporanModel;
    private ResultModel[] dataLaporan;

    /**
     * Creates new form Validasi
     */
    public Admini(ResultModel dataAkun) {
        initComponents();
        setTitle("Data Laporan");
        
        this.laporanModel = new models.Laporan();
        this.user = dataAkun;
        
        this.dataLaporan = this.laporanModel.allLaporanPetugas();
        this.tampilkanLaporan();
        
        // setting scrollbar
//        HelperClass.autoScroll(jPanel2, jPanel2.getWidth(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Verifikasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        back = new javax.swing.JToggleButton();
        Hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        verfy = new javax.swing.JButton();
        verfy1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Verifikasi.setBackground(new java.awt.Color(102, 153, 255));
        Verifikasi.setForeground(new java.awt.Color(102, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generate Lapporan");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_tanggapan", "id_pangaduan", "tgl_tanggapan", "tanggapan", "id_petugas"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setText("Back To Admin Page");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        edit.setText("Edit");

        verfy.setText("Batalkan Pilihan");
        verfy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verfyActionPerformed(evt);
            }
        });

        verfy1.setText("Veirifikasi");
        verfy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verfy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VerifikasiLayout = new javax.swing.GroupLayout(Verifikasi);
        Verifikasi.setLayout(VerifikasiLayout);
        VerifikasiLayout.setHorizontalGroup(
            VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerifikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(270, 270, 270))
            .addGroup(VerifikasiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verfy)
                    .addGroup(VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(VerifikasiLayout.createSequentialGroup()
                            .addComponent(verfy1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Hapus)
                            .addGap(267, 267, 267)
                            .addComponent(back))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        VerifikasiLayout.setVerticalGroup(
            VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerifikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(verfy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VerifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Hapus)
                    .addComponent(edit)
                    .addComponent(verfy1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Verifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Verifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void verfy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verfy1ActionPerformed
        // TODO add your handling code here
        int rowSelected = jTable2.getSelectedRow();
        if(rowSelected >= 0) {
            ResultModel laporanSelected = this.dataLaporan[rowSelected];
            if(laporanSelected.dByColumn("status").equals("0")) {
                String id = this.dataLaporan[rowSelected].dByColumn("id_pengaduan");
                boolean verif = this.laporanModel.verifikasi(id);
                
                if(verif) {
                    HelperClass.showAlert(this, 1, "Laporan berhasil diverifikasi");
                    setVisible(false);
                    new Admini(this.user).setVisible(true);
                } else {
                    HelperClass.showAlert(this, 0, "Laporan gagal di verifikasi, ERROR");
                }
                
            } else {
                HelperClass.showAlert(this, 0, "Laporan yang anda pilih sudah di verifikasi");
            }
            
        } else {
            HelperClass.showAlert(this, 0, "Harap pilih data laporan terlebih dahulu!");
        }
    }//GEN-LAST:event_verfy1ActionPerformed

    private void verfyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verfyActionPerformed
        // TODO add your handling code here:
        jTable2.clearSelection();
    }//GEN-LAST:event_verfyActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int rowSelected = jTable2.getSelectedRow();
        if(rowSelected >= 0) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data petugas?");
            if(konfirmasi == 0) {
                String id = this.dataLaporan[rowSelected].dByColumn("id_pengaduan");
                boolean delete = this.laporanModel.delete(id);
                
                if(delete) {
                    HelperClass.showAlert(this, 1, "Berhasil menghapus data laporan");
                    HelperClass.deleteRowTable(jTable2, rowSelected);
                    this.dataLaporan = this.laporanModel.allLaporanPetugas();
                } else {
                    HelperClass.showAlert(this, 0, "Gagal menghapus data laporan, ERROR.");
                }
            }
            
        } else {
            HelperClass.showAlert(this, 0, "Harap pilih data laporan terlebih dahulu!");
        }
    }//GEN-LAST:event_HapusActionPerformed

    
    public void tampilkanLaporan() {
        DefaultTableModel tModel = (DefaultTableModel) jTable2.getModel();
        for(int i=0; i < this.dataLaporan.length; i++) {
            ResultModel cDLaporan = this.dataLaporan[i];
            tModel.addRow(new String[] {
                cDLaporan.dByColumn("id_pengaduan"),
                cDLaporan.dByColumn("nama_masyarakat"),
                cDLaporan.dByColumn("tgl_pengaduan"),
                cDLaporan.dByColumn("status"),
            });
        }
        
        HelperClass.centerTabelCell(jTable2);
    }

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JPanel Verifikasi;
    private javax.swing.JToggleButton back;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton verfy;
    private javax.swing.JButton verfy1;
    // End of variables declaration//GEN-END:variables
}
